# output used in script F:\Xalt\Spectrum\TC1 Migration\DML\insert into spectrum_view table.sql


table_names = [
"CR_CHNG_REQ_BY_TYPE_MC","JC_JOB_MASTER","JC_JOB_MASTER2","JC_JOB_CHANGE_ORDER_TOTAL_MC","CR_CUSTOMER_MASTER","CR_OPEN_ITEMS_ALL_V","CR_PAYMENT_HISTORY_V","PR_DEPARTMENT","PR_RATE_REVISION","EC_EQUIPMENT_MASTER","JC_PHASE_ESTIMATE_TOTAL"
,"PA_NOTES","JC_ACTIVITY_BY_PERIOD","JC_PHASE_MASTER2_V","JC_PHASE_MASTER","VN_VENDOR_MASTER","JC_PHASE_PROJECTED_TOTAL","CR_TERMS_MASTER","PR_EMPLOYEE_MASTER","PR_TIME_OFF_BANK_CURRENT","WO_HEADER","WO_WO_ENTRY_V","WO_NOTES_MASTER_MC"
,"CR_CUSTOMER_MASTER1_V","CR_INVOICE_HEADER","JC_PHASE_LAST_PR_DATE","JC_ACTIVITY_BY_PERIOD_MC","JC_BILLED_PART1_MC","JC_BILLED_PART2_MC","JC_BILLED_SUMMARY_MC","JC_CO_AMT_PART1_MC","JC_CO_AMT_PART3_MC","JC_CO_AMT_PART5_MC","JC_PROJECTED_PART1_MC"
,"TM_JOB_MARKUP","GL_BALANCE1_V","GL_DETAIL1_V","GL_FISCAL_CALENDAR_DETAIL1_MC","GL_MASTER1_V","CR_AGING_DETAIL_MC","DI_MASTER_VIEW","JC_HISTORY_UNPOSTED_PR_V_MC","JC_JOB_MASTER_TOTAL_V","JC_PHASE_ESTIMATE_TOTAL_MC","WO_ADDRESS"
,"JC_TRANSACTION_HISTORY","GL_Detail","EC_EQUIPMENT_RATE_BY_JOB_MC","ET_EQUIPMENT_ISSUED","ET_REQ_HISTORY_DETAIL","ET_REQ_HISTORY_HEADER","PR_TIME_CARD_HISTORY","WO_HEADER4_V","PR_EMPLOYEE_MASTER_1_CRYPTO_MC","PR_EMPLOYEE_MASTER_MC"
,"GL_BALANCE","GL_MASTER","WO_Cost_History","GL_BUDGET"]

query = " UNION ALL\n".join([f"SELECT '{table_name}'" for table_name in table_names])

print(query)
