DELETE b FROM Forefront.dbo.CR_CHANGE_ORDER_HEADER_MC b JOIN Forefront_staging.dbo.CR_CHANGE_ORDER_HEADER_MC_DELETE d ON b.Change_Order_Number = d.Change_Order_Number AND b.Company_Code = d.Company_Code AND b.Customer_Code = d.Customer_Code AND b.Job_Number = d.Job_Number
DELETE b FROM Forefront.dbo.CR_CHANGE_ORDER_STATUS_MC b JOIN Forefront_staging.dbo.CR_CHANGE_ORDER_STATUS_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Status_Code = d.Status_Code
DELETE b FROM Forefront.dbo.CR_CHNG_ORD_REV_MC b JOIN Forefront_staging.dbo.CR_CHNG_ORD_REV_MC_DELETE d ON b.Bill_Group_Code = d.Bill_Group_Code AND b.Bill_Item_Code = d.Bill_Item_Code AND b.Billing_Item_Code = d.Billing_Item_Code AND b.Change_Request_Number = d.Change_Request_Number AND b.Company_Code = d.Company_Code AND b.Customer_Code = d.Customer_Code AND b.Job_Number = d.Job_Number AND b.System_Key = d.System_Key
DELETE b FROM Forefront.dbo.CR_CHNG_REQ_ADDON_MC b JOIN Forefront_staging.dbo.CR_CHNG_REQ_ADDON_MC_DELETE d ON b.Change_Request_Number = d.Change_Request_Number AND b.Company_Code = d.Company_Code AND b.Customer_Code = d.Customer_Code AND b.Job_Number = d.Job_Number AND b.Pricing_Addon_Code = d.Pricing_Addon_Code AND b.Sequence_Number = d.Sequence_Number
DELETE b FROM Forefront.dbo.CR_CHNG_REQ_CON_DET_MC b JOIN Forefront_staging.dbo.CR_CHNG_REQ_CON_DET_MC_DELETE d ON b.Change_Request_Number = d.Change_Request_Number AND b.Company_Code = d.Company_Code AND b.Customer_Code = d.Customer_Code AND b.Job_Number = d.Job_Number AND b.Sequence_Number = d.Sequence_Number
DELETE b FROM Forefront.dbo.CR_CHNG_REQ_HDR_MC b JOIN Forefront_staging.dbo.CR_CHNG_REQ_HDR_MC_DELETE d ON b.Change_Request_Number = d.Change_Request_Number AND b.Company_Code = d.Company_Code AND b.Customer_Code = d.Customer_Code AND b.Job_Number = d.Job_Number
DELETE b FROM Forefront.dbo.CR_CHNG_REQ_MARKUP_MC b JOIN Forefront_staging.dbo.CR_CHNG_REQ_MARKUP_MC_DELETE d ON b.Change_Request_Number = d.Change_Request_Number AND b.Company_Code = d.Company_Code AND b.Cost_Type = d.Cost_Type AND b.Customer_Code = d.Customer_Code AND b.Job_Number = d.Job_Number
DELETE b FROM Forefront.dbo.CR_CHNG_REQ_REV_MC b JOIN Forefront_staging.dbo.CR_CHNG_REQ_REV_MC_DELETE d ON b.Change_Request_Number = d.Change_Request_Number AND b.Company_Code = d.Company_Code AND b.Customer_Code = d.Customer_Code AND b.Job_Number = d.Job_Number AND b.Sequence = d.Sequence
DELETE b FROM Forefront.dbo.CR_CHNG_REQ_STATUS_MC b JOIN Forefront_staging.dbo.CR_CHNG_REQ_STATUS_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Status_Code = d.Status_Code
DELETE b FROM Forefront.dbo.CR_CONTRACT_MARKUP_MC b JOIN Forefront_staging.dbo.CR_CONTRACT_MARKUP_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Cost_Type = d.Cost_Type AND b.Customer_Code = d.Customer_Code AND b.Job_Number = d.Job_Number
DELETE b FROM Forefront.dbo.CR_CONTRACT_MASTER_MC b JOIN Forefront_staging.dbo.CR_CONTRACT_MASTER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Customer_Code = d.Customer_Code AND b.Job_Number = d.Job_Number
DELETE b FROM Forefront.dbo.CR_CONTRACT_PRICING_ADDON_MC b JOIN Forefront_staging.dbo.CR_CONTRACT_PRICING_ADDON_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Customer_Code = d.Customer_Code AND b.Job_Number = d.Job_Number AND b.Pricing_Addon_Code = d.Pricing_Addon_Code
DELETE b FROM Forefront.dbo.CR_CUST_USER_DEF_FIELDS_MC b JOIN Forefront_staging.dbo.CR_CUST_USER_DEF_FIELDS_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Customer_Code = d.Customer_Code AND b.User_Def_Sequence = d.User_Def_Sequence
DELETE b FROM Forefront.dbo.CR_CUSTOMER_MASTER_MC b JOIN Forefront_staging.dbo.CR_CUSTOMER_MASTER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Customer_Code = d.Customer_Code
DELETE b FROM Forefront.dbo.CR_DRAW_REQUEST_DETAIL_MC b JOIN Forefront_staging.dbo.CR_DRAW_REQUEST_DETAIL_MC_DELETE d ON b.Billing_Item_Code = d.Billing_Item_Code AND b.Company_Code = d.Company_Code AND b.Customer_Code = d.Customer_Code AND b.Job_Number = d.Job_Number
DELETE b FROM Forefront.dbo.CR_DRAW_UNIT_PRICE_BILL_MC b JOIN Forefront_staging.dbo.CR_DRAW_UNIT_PRICE_BILL_MC_DELETE d ON b.Bill_Group_Code = d.Bill_Group_Code AND b.Bill_Item_Code = d.Bill_Item_Code AND b.Company_Code = d.Company_Code AND b.Customer_Code = d.Customer_Code AND b.Job_Number = d.Job_Number
DELETE b FROM Forefront.dbo.CR_INVOICE_DETAIL_MC b JOIN Forefront_staging.dbo.CR_INVOICE_DETAIL_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Customer_Code = d.Customer_Code AND b.Invoice_Or_Transaction = d.Invoice_Or_Transaction AND b.Sequence = d.Sequence AND b.Transaction_Type = d.Transaction_Type
DELETE b FROM Forefront.dbo.CR_INVOICE_HEADER_MC b JOIN Forefront_staging.dbo.CR_INVOICE_HEADER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Customer_Code = d.Customer_Code AND b.Invoice_Or_Transaction = d.Invoice_Or_Transaction AND b.Transaction_Type = d.Transaction_Type
DELETE b FROM Forefront.dbo.CR_INVOICE_LOG_MC b JOIN Forefront_staging.dbo.CR_INVOICE_LOG_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Invoice_Or_Transaction = d.Invoice_Or_Transaction AND b.Transaction_Type = d.Transaction_Type
DELETE b FROM Forefront.dbo.CR_INVOICE_SPECIFIC_NOTES_MC b JOIN Forefront_staging.dbo.CR_INVOICE_SPECIFIC_NOTES_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Customer_Code = d.Customer_Code AND b.Internal_Sequence = d.Internal_Sequence AND b.Invoice_Number = d.Invoice_Number AND b.Invoice_Type = d.Invoice_Type AND b.Transaction_Type = d.Transaction_Type
DELETE b FROM Forefront.dbo.CR_OPEN_ITEM_MC b JOIN Forefront_staging.dbo.CR_OPEN_ITEM_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Customer_Code = d.Customer_Code AND b.Invoice_Or_Transaction = d.Invoice_Or_Transaction AND b.Reference = d.Reference AND b.Transaction_Type = d.Transaction_Type
DELETE b FROM Forefront.dbo.CR_PAY_ADJUST_HISTORY_MC b JOIN Forefront_staging.dbo.CR_PAY_ADJUST_HISTORY_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Customer_Code = d.Customer_Code AND b.Invoice_Or_Transaction = d.Invoice_Or_Transaction AND b.Payment_Number = d.Payment_Number AND b.Reference_Number = d.Reference_Number AND b.Transaction_Type = d.Transaction_Type
DELETE b FROM Forefront.dbo.CR_PRICING_ADDON_MC b JOIN Forefront_staging.dbo.CR_PRICING_ADDON_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Pricing_Addon_Code = d.Pricing_Addon_Code
DELETE b FROM Forefront.dbo.CR_SALES_TAX_MASTER_MC b JOIN Forefront_staging.dbo.CR_SALES_TAX_MASTER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Sales_Tax_Code = d.Sales_Tax_Code
DELETE b FROM Forefront.dbo.CR_TERMS_MASTER_MC b JOIN Forefront_staging.dbo.CR_TERMS_MASTER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Terms_Code = d.Terms_Code
DELETE b FROM Forefront.dbo.CR_UNIT_OF_MEASURE_MC b JOIN Forefront_staging.dbo.CR_UNIT_OF_MEASURE_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Unit_Of_Measure = d.Unit_Of_Measure
DELETE b FROM Forefront.dbo.DI_IMAGE_MASTER b JOIN Forefront_staging.dbo.DI_IMAGE_MASTER_DELETE d ON b.Document_ID = d.Document_ID
DELETE b FROM Forefront.dbo.DI_MASTER_MC b JOIN Forefront_staging.dbo.DI_MASTER_MC_DELETE d ON b.Cabinet = d.Cabinet AND b.Company_Code = d.Company_Code AND b.Drawer = d.Drawer AND b.Folder = d.Folder AND b.Reference = d.Reference
DELETE b FROM Forefront.dbo.EC_EQUIPMENT_MASTER_MC b JOIN Forefront_staging.dbo.EC_EQUIPMENT_MASTER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Equipment_Code = d.Equipment_Code
DELETE b FROM Forefront.dbo.EC_EQUIPMENT_STATUS_MC b JOIN Forefront_staging.dbo.EC_EQUIPMENT_STATUS_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Equipment_Status = d.Equipment_Status
DELETE b FROM Forefront.dbo.EC_JOB_EQUIPMENT_RATE_MC b JOIN Forefront_staging.dbo.EC_JOB_EQUIPMENT_RATE_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Equipment_Code = d.Equipment_Code AND b.Job_Number = d.Job_Number
DELETE b FROM Forefront.dbo.EC_YARD_MAINTENANCE_MC b JOIN Forefront_staging.dbo.EC_YARD_MAINTENANCE_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Yard_Code = d.Yard_Code
--EM_COST_CENTERS_MC
DELETE b FROM Forefront.dbo.EM_ENTITIES_MC b JOIN Forefront_staging.dbo.EM_ENTITIES_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Entity_Code = d.Entity_Code
DELETE b FROM Forefront.dbo.EM_ENTITY_TAX_XREF_MC b JOIN Forefront_staging.dbo.EM_ENTITY_TAX_XREF_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Entity_Code = d.Entity_Code AND b.Tax_Table_Code = d.Tax_Table_Code
DELETE b FROM Forefront.dbo.ET_EQUIPMENT_ISSUED_MC b JOIN Forefront_staging.dbo.ET_EQUIPMENT_ISSUED_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Equipment_Code = d.Equipment_Code
DELETE b FROM Forefront.dbo.ET_REQ_HISTORY_DETAIL_MC b JOIN Forefront_staging.dbo.ET_REQ_HISTORY_DETAIL_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Requisition_Sequence = d.Requisition_Sequence AND b.Tool_Requisition_Number = d.Tool_Requisition_Number
DELETE b FROM Forefront.dbo.ET_REQ_HISTORY_HEADER_MC b JOIN Forefront_staging.dbo.ET_REQ_HISTORY_HEADER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Tool_Requisition_Number = d.Tool_Requisition_Number
DELETE b FROM Forefront.dbo.GL_BALANCE_MC b JOIN Forefront_staging.dbo.GL_BALANCE_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Cost_Center = d.Cost_Center AND b.GL_Account = d.GL_Account AND b.Year = d.Year
DELETE b FROM Forefront.dbo.GL_BUDGET_MC b JOIN Forefront_staging.dbo.GL_BUDGET_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Cost_Center = d.Cost_Center AND b.GL_Account = d.GL_Account AND b.Year = d.Year
DELETE b FROM Forefront.dbo.GL_DEPARTMENT_MC b JOIN Forefront_staging.dbo.GL_DEPARTMENT_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Department_Code = d.Department_Code
DELETE b FROM Forefront.dbo.GL_DETAIL_MC b JOIN Forefront_staging.dbo.GL_DETAIL_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.GL_Account = d.GL_Account AND b.Gl_Period = d.Gl_Period AND b.Tran_Number = d.Tran_Number AND b.Tran_Ref_Days = d.Tran_Ref_Days AND b.Year = d.Year
DELETE b FROM Forefront.dbo.GL_FISCAL_CALENDAR_DETAIL b JOIN Forefront_staging.dbo.GL_FISCAL_CALENDAR_DETAIL_DELETE d ON b.Company_Code = d.Company_Code AND b.End_Date = d.End_Date AND b.Start_Date = d.Start_Date
DELETE b FROM Forefront.dbo.GL_MASTER_MC b JOIN Forefront_staging.dbo.GL_MASTER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.GL_Account = d.GL_Account
DELETE b FROM Forefront.dbo.HR_EMP_DEPENDENTS_MC b JOIN Forefront_staging.dbo.HR_EMP_DEPENDENTS_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Employee_Code = d.Employee_Code AND b.Employee_Dependent_Seq = d.Employee_Dependent_Seq
DELETE b FROM Forefront.dbo.IM_ITEM_MASTER_MC b JOIN Forefront_staging.dbo.IM_ITEM_MASTER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Item_Code = d.Item_Code
DELETE b FROM Forefront.dbo.IM_REQUISITION_DETAIL_MC b JOIN Forefront_staging.dbo.IM_REQUISITION_DETAIL_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Requisition_Sequence = d.Requisition_Sequence AND b.Transaction_Reference = d.Transaction_Reference AND b.Transaction_Sequence = d.Transaction_Sequence AND b.Transfer_Type = d.Transfer_Type
DELETE b FROM Forefront.dbo.IM_REQUISITION_HEADER_MC b JOIN Forefront_staging.dbo.IM_REQUISITION_HEADER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Requisition_Sequence = d.Requisition_Sequence AND b.Transaction_Reference = d.Transaction_Reference AND b.Transfer_Type = d.Transfer_Type
DELETE b FROM Forefront.dbo.IM_TRANSACTION_HISTORY_MC b JOIN Forefront_staging.dbo.IM_TRANSACTION_HISTORY_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Requisition_Sequence = d.Requisition_Sequence AND b.Transaction_Reference = d.Transaction_Reference AND b.Transaction_Sequence = d.Transaction_Sequence AND b.Transfer_Flag = d.Transfer_Flag AND b.Transfer_Type = d.Transfer_Type
DELETE b FROM Forefront.dbo.JC_ALT_BILLING_MC b JOIN Forefront_staging.dbo.JC_ALT_BILLING_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Invoice_Number = d.Invoice_Number AND b.Job_Number = d.Job_Number
DELETE b FROM Forefront.dbo.JC_BAL_YR_PER_RANGE_MC b JOIN Forefront_staging.dbo.JC_BAL_YR_PER_RANGE_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Terminal_ID = d.Terminal_ID AND b.Use_Code = d.Use_Code
DELETE b FROM Forefront.dbo.JC_CM_COMMITTED_H_MC b JOIN Forefront_staging.dbo.JC_CM_COMMITTED_H_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Cost_Type = d.Cost_Type AND b.Currency_Code = d.Currency_Code AND b.Job_Number = d.Job_Number AND b.Phase_Code = d.Phase_Code
DELETE b FROM Forefront.dbo.JC_COST_TYPE_MASTER_MC b JOIN Forefront_staging.dbo.JC_COST_TYPE_MASTER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Cost_Type = d.Cost_Type
DELETE b FROM Forefront.dbo.JC_EARNED_REVENUE_HISTORY_MC b JOIN Forefront_staging.dbo.JC_EARNED_REVENUE_HISTORY_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Job_Number = d.Job_Number AND b.Transaction_Date = d.Transaction_Date
DELETE b FROM Forefront.dbo.JC_JOB_CONTACTS_MC b JOIN Forefront_staging.dbo.JC_JOB_CONTACTS_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Contact_ID = d.Contact_ID AND b.Job_Number = d.Job_Number
DELETE b FROM Forefront.dbo.JC_JOB_MASTER_MC b JOIN Forefront_staging.dbo.JC_JOB_MASTER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Job_Number = d.Job_Number
DELETE b FROM Forefront.dbo.JC_JOB_USER_FIELDS_DET_MC b JOIN Forefront_staging.dbo.JC_JOB_USER_FIELDS_DET_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Job_Number = d.Job_Number AND b.User_Def_Sequence = d.User_Def_Sequence
DELETE b FROM Forefront.dbo.JC_PHASE_ESTIMATES_MC b JOIN Forefront_staging.dbo.JC_PHASE_ESTIMATES_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Cost_Type = d.Cost_Type AND b.Job_Number = d.Job_Number AND b.Phase_Code = d.Phase_Code
DELETE b FROM Forefront.dbo.JC_PHASE_MASTER_MC b JOIN Forefront_staging.dbo.JC_PHASE_MASTER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Cost_Type = d.Cost_Type AND b.Job_Number = d.Job_Number AND b.Phase_Code = d.Phase_Code
DELETE b FROM Forefront.dbo.JC_PROJ_COST_HISTORY_MC b JOIN Forefront_staging.dbo.JC_PROJ_COST_HISTORY_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Cost_Type = d.Cost_Type AND b.Job = d.Job AND b.Phase = d.Phase AND b.System_Key = d.System_Key AND b.Type = d.Type
DELETE b FROM Forefront.dbo.JC_QUANTITY_HISTORY_MC b JOIN Forefront_staging.dbo.JC_QUANTITY_HISTORY_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Cost_Type = d.Cost_Type AND b.Day_Entered = d.Day_Entered AND b.Job_Number = d.Job_Number AND b.Period_End_Date = d.Period_End_Date AND b.Phase_Code = d.Phase_Code AND b.Quantity_Key = d.Quantity_Key
DELETE b FROM Forefront.dbo.JC_STD_PHASE_DESCRIPTION_MC b JOIN Forefront_staging.dbo.JC_STD_PHASE_DESCRIPTION_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Phase_Code = d.Phase_Code
DELETE b FROM Forefront.dbo.JC_TRANSACTION_HISTORY_MC b JOIN Forefront_staging.dbo.JC_TRANSACTION_HISTORY_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Cost_Type = d.Cost_Type AND b.Detail_Sequence = d.Detail_Sequence AND b.Job_Number = d.Job_Number AND b.Phase_Code = d.Phase_Code AND b.Reference_1 = d.Reference_1 AND b.Reference_2 = d.Reference_2 AND b.Tran_Date_Text = d.Tran_Date_Text AND b.Tran_Type_Code = d.Tran_Type_Code
DELETE b FROM Forefront.dbo.MC_CURRENCY_EXCHANGE_RATES_MC b JOIN Forefront_staging.dbo.MC_CURRENCY_EXCHANGE_RATES_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Currency_Code = d.Currency_Code AND b.Effective_Date = d.Effective_Date
DELETE b FROM Forefront.dbo.MC_CURRENCY_MASTER_MC b JOIN Forefront_staging.dbo.MC_CURRENCY_MASTER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Currency_Code = d.Currency_Code
DELETE b FROM Forefront.dbo.PA_ADDRESS_MASTER b JOIN Forefront_staging.dbo.PA_ADDRESS_MASTER_DELETE d ON b.Addr_ID = d.Addr_ID
DELETE b FROM Forefront.dbo.PA_COMPANY_INFORMATION b JOIN Forefront_staging.dbo.PA_COMPANY_INFORMATION_DELETE d ON b.Company_Code = d.Company_Code
DELETE b FROM Forefront.dbo.PA_CONTACTS_MASTER b JOIN Forefront_staging.dbo.PA_CONTACTS_MASTER_DELETE d ON b.Contact_ID = d.Contact_ID
DELETE b FROM Forefront.dbo.PA_CONTROL_FILE_MC b JOIN Forefront_staging.dbo.PA_CONTROL_FILE_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Record_ID = d.Record_ID
--PA_GLOBAL_BUSINESS_UNIT_MAP
--PA_GLOBAL_ENTITY_MAP
--PA_GLOBAL_USER_MAP
--PA_LOCAL_COMPANY_MAP
DELETE b FROM Forefront.dbo.PA_NOTES_MC b JOIN Forefront_staging.dbo.PA_NOTES_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Notes_Key = d.Notes_Key AND b.Notes_Topic = d.Notes_Topic AND b.Notes_Type = d.Notes_Type
DELETE b FROM Forefront.dbo.PA_OPERATOR_FILE_MC b JOIN Forefront_staging.dbo.PA_OPERATOR_FILE_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Operator_Id = d.Operator_Id
DELETE b FROM Forefront.dbo.PA_OPERATOR_MASTER b JOIN Forefront_staging.dbo.PA_OPERATOR_MASTER_DELETE d ON b.Operator_ID = d.Operator_ID
DELETE b FROM Forefront.dbo.PA_PHONE_MASTER b JOIN Forefront_staging.dbo.PA_PHONE_MASTER_DELETE d ON b.Phone_ID = d.Phone_ID
DELETE b FROM Forefront.dbo.PA_USER_FIELDS_SETUP_U_MC b JOIN Forefront_staging.dbo.PA_USER_FIELDS_SETUP_U_MC_DELETE d ON b.Entry_Type = d.Entry_Type AND b.Sequence = d.Sequence
DELETE b FROM Forefront.dbo.PA_VALUE_VARIABLES b JOIN Forefront_staging.dbo.PA_VALUE_VARIABLES_DELETE d ON b.Company_or_All = d.Company_or_All AND b.Variable_Name = d.Variable_Name
DELETE b FROM Forefront.dbo.PJ_CORRESPONDENCE_HEADER_MC b JOIN Forefront_staging.dbo.PJ_CORRESPONDENCE_HEADER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Job_Number = d.Job_Number AND b.TransactionId = d.TransactionId
DELETE b FROM Forefront.dbo.PO_BLANKET_RELEASE_HEADER_MC b JOIN Forefront_staging.dbo.PO_BLANKET_RELEASE_HEADER_MC_DELETE d ON b.Blanket_Release = d.Blanket_Release AND b.Company_Code = d.Company_Code AND b.PO_Number = d.PO_Number
DELETE b FROM Forefront.dbo.PO_PURCHASE_ORDER_DETAIL_MC b JOIN Forefront_staging.dbo.PO_PURCHASE_ORDER_DETAIL_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Line_Number = d.Line_Number AND b.PO_Number = d.PO_Number
DELETE b FROM Forefront.dbo.PO_PURCHASE_ORDER_HEADER_MC b JOIN Forefront_staging.dbo.PO_PURCHASE_ORDER_HEADER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.PO_Number = d.PO_Number
DELETE b FROM Forefront.dbo.PR_BASE_WORK_COMP_MC b JOIN Forefront_staging.dbo.PR_BASE_WORK_COMP_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Worker_Comp_Class_Code = d.Worker_Comp_Class_Code
DELETE b FROM Forefront.dbo.PR_CHECK_HISTORY_MC b JOIN Forefront_staging.dbo.PR_CHECK_HISTORY_MC_DELETE d ON b.Check_Number = d.Check_Number AND b.Check_Type = d.Check_Type AND b.Company_Code = d.Company_Code AND b.Employee_Code = d.Employee_Code
DELETE b FROM Forefront.dbo.PR_DEPARTMENT_MC b JOIN Forefront_staging.dbo.PR_DEPARTMENT_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Department_Code = d.Department_Code
DELETE b FROM Forefront.dbo.PR_EMPL_VOL_DEDUCT_MC b JOIN Forefront_staging.dbo.PR_EMPL_VOL_DEDUCT_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Employee_Code = d.Employee_Code AND b.Vol_Deduct_Code = d.Vol_Deduct_Code
DELETE b FROM Forefront.dbo.PR_EMPLOYEE_ENTITY_MASTER_2_MC b JOIN Forefront_staging.dbo.PR_EMPLOYEE_ENTITY_MASTER_2_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Employee_Code = d.Employee_Code AND b.Entity_Code = d.Entity_Code
DELETE b FROM Forefront.dbo.PR_EMPLOYEE_LAST_ENTRIES_MC b JOIN Forefront_staging.dbo.PR_EMPLOYEE_LAST_ENTRIES_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Employee_Code = d.Employee_Code
DELETE b FROM Forefront.dbo.PR_EMPLOYEE_MASTER_1_MC b JOIN Forefront_staging.dbo.PR_EMPLOYEE_MASTER_1_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Employee_Code = d.Employee_Code
DELETE b FROM Forefront.dbo.PR_EMPLOYEE_MASTER_2_MC b JOIN Forefront_staging.dbo.PR_EMPLOYEE_MASTER_2_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Employee_Code = d.Employee_Code
DELETE b FROM Forefront.dbo.PR_EMPLOYEE_MASTER_3_MC b JOIN Forefront_staging.dbo.PR_EMPLOYEE_MASTER_3_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Employee_Code = d.Employee_Code
DELETE b FROM Forefront.dbo.PR_EMPLOYEE_STATUS_MC b JOIN Forefront_staging.dbo.PR_EMPLOYEE_STATUS_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Status_Code = d.Status_Code
DELETE b FROM Forefront.dbo.PR_INCOME_TAX_TABLE_MC b JOIN Forefront_staging.dbo.PR_INCOME_TAX_TABLE_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Tax_Table_Code = d.Tax_Table_Code
DELETE b FROM Forefront.dbo.PR_PRE_TIME_CARD_MC b JOIN Forefront_staging.dbo.PR_PRE_TIME_CARD_MC_DELETE d ON b.Check_Sequence_Number = d.Check_Sequence_Number AND b.Company_Code = d.Company_Code AND b.Employee_Code = d.Employee_Code AND b.System_Key = d.System_Key
DELETE b FROM Forefront.dbo.PR_RATE_REVISION_MC b JOIN Forefront_staging.dbo.PR_RATE_REVISION_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Employee_Code = d.Employee_Code AND b.Rate_Type = d.Rate_Type AND b.System_Key = d.System_Key
DELETE b FROM Forefront.dbo.PR_TIME_CARD_DETAIL_MC b JOIN Forefront_staging.dbo.PR_TIME_CARD_DETAIL_MC_DELETE d ON b.Check_Sequence_Number = d.Check_Sequence_Number AND b.Company_Code = d.Company_Code AND b.Employee_Code = d.Employee_Code AND b.System_Key = d.System_Key
DELETE b FROM Forefront.dbo.PR_TIME_CARD_HISTORY_MC b JOIN Forefront_staging.dbo.PR_TIME_CARD_HISTORY_MC_DELETE d ON b.Check_Sequence_Number = d.Check_Sequence_Number AND b.Company_Code = d.Company_Code AND b.Employee_Code = d.Employee_Code AND b.System_Key = d.System_Key
DELETE b FROM Forefront.dbo.PR_TIME_OFF_ANNIVERSARY_MC b JOIN Forefront_staging.dbo.PR_TIME_OFF_ANNIVERSARY_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Employee_Code = d.Employee_Code AND b.Entity_Code = d.Entity_Code AND b.Pay_Type = d.Pay_Type
DELETE b FROM Forefront.dbo.PR_TIME_OFF_BANK_LOG_MC b JOIN Forefront_staging.dbo.PR_TIME_OFF_BANK_LOG_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Effective_Date = d.Effective_Date AND b.Employee_Code = d.Employee_Code AND b.Entity_Code = d.Entity_Code AND b.Internal_Key = d.Internal_Key AND b.Pay_Type = d.Pay_Type
DELETE b FROM Forefront.dbo.PR_UNION_MASTER_1_MC b JOIN Forefront_staging.dbo.PR_UNION_MASTER_1_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Union_Code = d.Union_Code
DELETE b FROM Forefront.dbo.PR_VAC_HOL_SICK_MASTER_MC b JOIN Forefront_staging.dbo.PR_VAC_HOL_SICK_MASTER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Control_Code = d.Control_Code
DELETE b FROM Forefront.dbo.PR_W2_HISTORY_MC b JOIN Forefront_staging.dbo.PR_W2_HISTORY_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Employee_Code = d.Employee_Code AND b.Entity_Code = d.Entity_Code AND b.Form_Number = d.Form_Number AND b.History_Year = d.History_Year
DELETE b FROM Forefront.dbo.PR_WAGE_CLASS_MASTER_MC b JOIN Forefront_staging.dbo.PR_WAGE_CLASS_MASTER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Union_Code = d.Union_Code AND b.Wage_Code = d.Wage_Code
DELETE b FROM Forefront.dbo.PR_WORK_CLASS_MC b JOIN Forefront_staging.dbo.PR_WORK_CLASS_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.State = d.State AND b.Worker_Comp_Class_Code = d.Worker_Comp_Class_Code
DELETE b FROM Forefront.dbo.SC_CONTRACT_MC b JOIN Forefront_staging.dbo.SC_CONTRACT_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Contract_Number = d.Contract_Number AND b.Site_ID = d.Site_ID
DELETE b FROM Forefront.dbo.SC_CONTRACT_USER_FIELDS_MC b JOIN Forefront_staging.dbo.SC_CONTRACT_USER_FIELDS_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Contract_Number = d.Contract_Number AND b.Site_ID = d.Site_ID AND b.User_Def_Sequence = d.User_Def_Sequence
DELETE b FROM Forefront.dbo.TM_JOB_MARKUP_MC b JOIN Forefront_staging.dbo.TM_JOB_MARKUP_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Job_Number = d.Job_Number AND b.Sequence = d.Sequence
DELETE b FROM Forefront.dbo.TM_LABOR_BILLING_RATES_MC b JOIN Forefront_staging.dbo.TM_LABOR_BILLING_RATES_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Labor_Bill_Rate_Code = d.Labor_Bill_Rate_Code
DELETE b FROM Forefront.dbo.VN_CHNG_REQ_SUB_DET_MC b JOIN Forefront_staging.dbo.VN_CHNG_REQ_SUB_DET_MC_DELETE d ON b.Bid_Item_Code = d.Bid_Item_Code AND b.Change_Request_Number = d.Change_Request_Number AND b.Company_Code = d.Company_Code AND b.Cost_Type = d.Cost_Type AND b.Customer_Code = d.Customer_Code AND b.Job_Number = d.Job_Number AND b.Phase_Code = d.Phase_Code AND b.Subcontract_Number = d.Subcontract_Number AND b.Subcontractor_Code = d.Subcontractor_Code
DELETE b FROM Forefront.dbo.VN_CHNG_REQ_SUB_HDR_MC b JOIN Forefront_staging.dbo.VN_CHNG_REQ_SUB_HDR_MC_DELETE d ON b.Change_Request_Number = d.Change_Request_Number AND b.Company_Code = d.Company_Code AND b.Customer_Code = d.Customer_Code AND b.Job_Number = d.Job_Number AND b.Subcontract_Number = d.Subcontract_Number AND b.Subcontractor_Code = d.Subcontractor_Code
DELETE b FROM Forefront.dbo.VN_GL_DISTRIBUTION_DETAIL_MC b JOIN Forefront_staging.dbo.VN_GL_DISTRIBUTION_DETAIL_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Invoice_Number = d.Invoice_Number AND b.Invoice_Type_Code = d.Invoice_Type_Code AND b.Sequence = d.Sequence AND b.Vendor_Code = d.Vendor_Code
DELETE b FROM Forefront.dbo.VN_GL_DISTRIBUTION_HEADER_MC b JOIN Forefront_staging.dbo.VN_GL_DISTRIBUTION_HEADER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Invoice_Number = d.Invoice_Number AND b.Invoice_Type_Code = d.Invoice_Type_Code AND b.Vendor_Code = d.Vendor_Code
--VN_SUBCONTRACT_MC
DELETE b FROM Forefront.dbo.VN_SUBCONTRACT_PHASE_MC b JOIN Forefront_staging.dbo.VN_SUBCONTRACT_PHASE_MC_DELETE d ON b.Bid_Item_Number = d.Bid_Item_Number AND b.Company_Code = d.Company_Code AND b.Cost_Type = d.Cost_Type AND b.Phase_Code = d.Phase_Code AND b.Subcontract_Number = d.Subcontract_Number AND b.Vendor_Code = d.Vendor_Code
DELETE b FROM Forefront.dbo.VN_VENDOR_CURRENCY_OVERRIDE_MC b JOIN Forefront_staging.dbo.VN_VENDOR_CURRENCY_OVERRIDE_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Vendor_Code = d.Vendor_Code
DELETE b FROM Forefront.dbo.VN_VENDOR_LOCATIONS_MC b JOIN Forefront_staging.dbo.VN_VENDOR_LOCATIONS_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Location_Code = d.Location_Code AND b.Vendor_Code = d.Vendor_Code
DELETE b FROM Forefront.dbo.VN_VENDOR_MASTER_MC b JOIN Forefront_staging.dbo.VN_VENDOR_MASTER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Vendor_Code = d.Vendor_Code
DELETE b FROM Forefront.dbo.WO_ADDRESS_MC b JOIN Forefront_staging.dbo.WO_ADDRESS_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Ship_To_ID = d.Ship_To_ID
DELETE b FROM Forefront.dbo.WO_BILLING_HISTORY_MC b JOIN Forefront_staging.dbo.WO_BILLING_HISTORY_MC_DELETE d ON b.Bill_Number = d.Bill_Number AND b.Company_Code = d.Company_Code AND b.Customer_Code = d.Customer_Code AND b.Invoice_Number = d.Invoice_Number AND b.Invoice_Type = d.Invoice_Type AND b.WO_Number = d.WO_Number
DELETE b FROM Forefront.dbo.WO_CASE_TYPE_MC b JOIN Forefront_staging.dbo.WO_CASE_TYPE_MC_DELETE d ON b.Case_Type_Code = d.Case_Type_Code AND b.Company_Code = d.Company_Code
DELETE b FROM Forefront.dbo.WO_COMPONENT_MC b JOIN Forefront_staging.dbo.WO_COMPONENT_MC_DELETE d ON b.Com_ID = d.Com_ID AND b.Company_Code = d.Company_Code AND b.Equip_ID = d.Equip_ID AND b.Site_ID = d.Site_ID
DELETE b FROM Forefront.dbo.WO_COST_HISTORY_MC b JOIN Forefront_staging.dbo.WO_COST_HISTORY_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Component_Id = d.Component_Id AND b.Equipment_Id = d.Equipment_Id AND b.Reference = d.Reference AND b.Tran_Source = d.Tran_Source AND b.Tran_Type = d.Tran_Type AND b.WO_Number = d.WO_Number
DELETE b FROM Forefront.dbo.WO_DISPATCH_STATUS_MC b JOIN Forefront_staging.dbo.WO_DISPATCH_STATUS_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.WO_Dispatch_Status = d.WO_Dispatch_Status
--WO_EMPL_HOURS_HIST_DETAIL_MC
--WO_EMPL_LABOR_HOURS_DET_MC
DELETE b FROM Forefront.dbo.WO_EMPLOYEE_CATEGORY_MC b JOIN Forefront_staging.dbo.WO_EMPLOYEE_CATEGORY_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Employee_Code = d.Employee_Code
DELETE b FROM Forefront.dbo.WO_HEADER_MC b JOIN Forefront_staging.dbo.WO_HEADER_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.WO_Number = d.WO_Number
DELETE b FROM Forefront.dbo.WO_PRIORITY_MC b JOIN Forefront_staging.dbo.WO_PRIORITY_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.WO_Priority = d.WO_Priority
DELETE b FROM Forefront.dbo.WO_TYPE_MC b JOIN Forefront_staging.dbo.WO_TYPE_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.WO_Type = d.WO_Type
DELETE b FROM Forefront.dbo.WO_WO_USER_FIELDS_DET_MC b JOIN Forefront_staging.dbo.WO_WO_USER_FIELDS_DET_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.User_Def_Sequence = d.User_Def_Sequence AND b.WO_Number = d.WO_Number
DELETE b FROM Forefront.dbo.WO_ZONE_MC b JOIN Forefront_staging.dbo.WO_ZONE_MC_DELETE d ON b.Company_Code = d.Company_Code AND b.Zone = d.Zone
